### ISSUE TITLE
networkx 2.0 no longer allows providing an attribute dict as an argument

### ISSUE THREAD

**Issue by toddrme2178** [hsharrison/experimentator#24]
As of networkx 2.0, you can no longer [specify an attribute dict as a positional argument](https://github.com/networkx/networkx/pull/2132).  This breaks experimentator's `ExperimentSection` class [here](https://github.com/hsharrison/experimentator/blob/v0.3.1/src/experimentator/section.py#L171).  You now just unpack the dict.

**Comment by hsharrison** [comment]
Thanks for the heads up.
